
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://spring-config-server:8080
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: health,info,busrefresh
